#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "virtualtabletop"
name = "VirtualTabletop"
description.en = "Virtual surface in the browser on which you can play board, dice and card games"
description.fr = "Surface virtuelle dans le navigateur sur laquelle vous pouvez jouer à des jeux de société, de dés et de cartes"

version = "2025.10.30~ynh1"

maintainers = ["trendless"]

[upstream]
license = "GPL-3.0-only"
demo = "https://virtualtabletop.io"
admindoc = "https://github.com/ArnoldSmith86/virtualtabletop/wiki"
userdoc = "https://github.com/ArnoldSmith86/virtualtabletop/wiki/Playing-Games"
code = "https://github.com/ArnoldSmith86/virtualtabletop"
fund = "https://www.patreon.com/virtualtabletop"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "1G"
ram.build = "500M"
ram.runtime = "250M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/ArnoldSmith86/virtualtabletop/archive/43344715ac1e133d6122721856031e05c503b6c9.tar.gz"
    sha256 = "c8c00201f22239a0b891c44b874552ecb7aaad24dd8cb9105a95b649e66b83ab"

    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    admin.url = "/stats"
    admin.show_tile = false
    admin.allowed = "admins"

    [resources.ports]
    main.default = 8272

    [resources.nodejs]
    version = "18"
